## What are Tensors?
### A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.
### In the general case, an array of numbers arranged on a regular grid with a variable number of axes is known as a tensor [1].

#### 1. https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/

 
 ## This notebook is following and borrows from
 ###### https://youtube.com/playlist?list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4

In [4]:
import torch
x = torch.empty(5, dtype=torch.int32)
print(x)
print(x.dtype)
print(x.size())

tensor([1916366112,      32523, 1916366112,      32523,         32],
       dtype=torch.int32)
torch.int32
torch.Size([5])


In [5]:
x = torch.zeros(5)
print(x)

tensor([0., 0., 0., 0., 0.])


In [6]:
x = torch.ones(5)
print(x)

tensor([1., 1., 1., 1., 1.])


In [7]:
x = torch.rand(2, 4)
print(x)

tensor([[0.4541, 0.4800, 0.7946, 0.3814],
        [0.0335, 0.7801, 0.6789, 0.5361]])


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
### We can also create tensors from other python data types such as lists or numpy arrays

In [17]:
x = torch.tensor([2, 3, 6, 8, 79])
print(x)

tensor([ 2,  3,  6,  8, 79])


In [18]:
import numpy as np
y = np.array([2, 3, 5, 8, 79])
x = torch.from_numpy(y)
print(x)

tensor([ 2,  3,  5,  8, 79])


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
### Now Let's see about some basic tensor operations

In [8]:
x = torch.rand(2)
y = torch.rand(2)

print(x)
print(y)

print()
print("#################")

print("Summation", x+y)
print("Subtraction", x-y)

# OR
print()
print("#################")

print("Summation", torch.add(x,y))
print("Subtraction", torch.sub(x,y))

tensor([0.6202, 0.8928])
tensor([0.8578, 0.7175])

#################
Summation tensor([1.4780, 1.6104])
Subtraction tensor([-0.2375,  0.1753])

#################
Summation tensor([1.4780, 1.6104])
Subtraction tensor([-0.2375,  0.1753])


In [27]:
print("Multiplication", torch.mul(x,y))
print("Division", torch.div(x,y))

Multiplication tensor([0.3633, 0.1856])
Division tensor([1.4387, 4.6584])


In [28]:
x = torch.rand(3, 5)
print(x)
print(x[1, 2].item())

tensor([[0.5853, 0.7460, 0.9700, 0.6414, 0.4475],
        [0.7837, 0.0480, 0.6598, 0.7582, 0.2965],
        [0.6757, 0.8456, 0.2697, 0.5810, 0.4508]])
0.6598471403121948


In [9]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5)
    x = x.to(device)