# The autograd package and calculation of gradients
## Here, we will see how the autograd from PyTorch can be used to calculate the gradient of a funciton with respect to its parameters
 
 ## This notebook is following and borrows from
 ###### https://youtube.com/playlist?list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4
 
 

In [15]:
import torch

x = torch.rand(1, requires_grad=True)
print(x)

tensor([0.2549], requires_grad=True)


In [16]:
y = x * 5

In [17]:
print(y)

tensor([1.2745], grad_fn=<MulBackward0>)


In [18]:
z = y + 45
print(z)

tensor([46.2745], grad_fn=<AddBackward0>)


In [19]:
print(x.grad)
z.backward()
print(x.grad)

None
tensor([5.])


## What happens when we do not want autograd to calculate gradiants and update one of our parameters

### We can simply .detach() the parameter from the autograd gradient tree

In [38]:
x.requires_grad_(False)

tensor([0.4239])

In [39]:
print(x)

tensor([0.4239])


### OR we can use the torch nograd function
### This function stops the autograd package from constructing the gradient tree

In [20]:
x = torch.rand(1, requires_grad=True)
print(x)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([0.8407], requires_grad=True)
tensor([2.8407])


### Whenever we call the backward function new gradient values will be accumulated in the previous grad values
### To stop this from happening, we need to set the gradient to zero in each epoch of our training
### This is done by 

In [22]:
x = torch.rand(1, requires_grad=True)
for i in range(4):
    y = x * 4
    z = y + 45
    z.backward();
    print(x.grad)

tensor([4.])
tensor([8.])
tensor([12.])
tensor([16.])


In [24]:
x = torch.rand(1, requires_grad=True)
for i in range(4):
    y = x * 4
    z = y + 45
    z.backward();
    print(x.grad)
    x.grad.zero_()

tensor([4.])
tensor([4.])
tensor([4.])
tensor([4.])
